import streamlit as st
import pandas as pd
import joblib

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="AgroSmart | AI Support",
    page_icon="🌱",
    layout="wide", # Using wide layout for better column spacing
)

# --- CUSTOM CSS ---
st.markdown("""
    <style>
    .main {
        background-color: #f5f7f9;
    }
    .stButton>button {
        width: 100%;
        border-radius: 5px;
        height: 3em;
        background-color: #2e7d32;
        color: white;
    }
    .result-card {
        padding: 20px;
        border-radius: 10px;
        background-color: #ffffff;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    </style>
    """, unsafe_allow_html=True)

# --- LOAD MODELS ---
@st.cache_resource # Cache models so they don't reload on every interaction
def load_assets():
    crop_model = joblib.load("models/crop_model.pkl")
    fertilizer_model = joblib.load("models/fertilizer_model.pkl")
    crop_encoder = joblib.load("models/crop_label_encoder.pkl")
    fertilizer_encoder = joblib.load("models/fertilizer_label_encoder.pkl")
    return crop_model, fertilizer_model, crop_encoder, fertilizer_encoder

crop_model, fertilizer_model, crop_encoder, fertilizer_encoder = load_assets()

# --- HEADER ---
st.title("🌾 Smart Agriculture Decision Support")
st.markdown("Optimize your yield using machine learning insights based on real-time soil and climate data.")
st.divider()

# --- INPUT SECTION ---
col1, col2 = st.columns([1, 2], gap="large")

with col1:
    st.subheader("📊 Soil Composition")
    N = st.number_input("Nitrogen (N)", 0, 200, 90, help="Nitrogen content in soil")
    P = st.number_input("Phosphorous (P)", 0, 200, 40)
    K = st.number_input("Potassium (K)", 0, 200, 40)
    ph = st.slider("Soil pH Level", 0.0, 14.0, 6.5, step=0.1)

with col2:
    st.subheader("☁️ Environmental Factors")
    c1, c2 = st.columns(2)
    with c1:
        temperature = st.number_input("Temperature (°C)", 0.0, 50.0, 25.0)
        rainfall = st.number_input("Rainfall (mm)", 0.0, 500.0, 200.0)
    with c2:
        humidity = st.number_input("Humidity (%)", 0.0, 100.0, 80.0)
    
    st.write("---")
    predict_btn = st.button("🚀 Generate Recommendation")

# --- PREDICTION LOGIC ---
if predict_btn:
    input_data = pd.DataFrame([{
        'N': N, 'P': P, 'K': K,
        'temperature': temperature,
        'humidity': humidity,
        'ph': ph,
        'rainfall': rainfall
    }])

    # Predictions
    crop_pred_encoded = crop_model.predict(input_data)[0]
    crop_pred = crop_encoder.inverse_transform([crop_pred_encoded])[0]

    fertilizer_input = input_data.copy()
    fertilizer_input['label'] = crop_pred
    fert_pred_encoded = fertilizer_model.predict(fertilizer_input)[0]
    fert_pred = fertilizer_encoder.inverse_transform([fert_pred_encoded])[0]

    # --- DISPLAY RESULTS ---
    st.subheader("🎯 Analysis Results")
    res_col1, res_col2 = st.columns(2)

    with res_col1:
        st.success(f"### Best Crop to Plant\n# **{crop_pred.upper()}**")
    
    with res_col2:
        st.info(f"### Recommended Fertilizer\n# **{fert_pred}**")

    st.warning("**Note:** These results are generated by an AI model. Please cross-reference with local soil testing reports before application.")